AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LambyRails Lambda (HTTP API)

Parameters:

  RailsEnv:
    Type: String
    Default: production
    AllowedValues:
      - staging
      - production

Resources:

  RailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: ruby2.7
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          RAILS_ENV: !Ref RailsEnv
      FunctionName: !Join [ '', [ 'LambyRails-', !Ref RailsEnv, '-', !Ref 'AWS::Region' ] ]
      Events:
        RailsApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref RailsApi
      AutoPublishAlias: live

  RailsApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref RailsEnv

Outputs:

  RailsApiUrl:
    Description: API Gateway Endpoint
    Value: !Sub "https://${RailsApi}.execute-api.${AWS::Region}.amazonaws.com/${RailsEnv}/"

  RailsFunctionArn:
    Description: Lambda ARN
    Value: !GetAtt RailsFunction.Arn
